from typing import List, Optional
from ..schemas import EpisodicEvent, EpisodeFrame
from .split_engine import SplitEngine
from .merge_engine import MergeEngine
from .similarity import SignatureSimilarityEvaluator


class EpisodeRefiner:
    """
    Main orchestrator for Stage 1 — Part C: Episode Refinement.

    Refines temporary EpisodicEvents produced by EpisodeBuilder by:
      1. Splitting events with internal behavioral discontinuities (SplitEngine).
      2. Merging temporally adjacent events with continuous behavioral identity (MergeEngine).

    Operates purely locally on the generated pipeline output without external database,
    LLM, or retrieval dependencies.
    """

    def __init__(
        self,
        split_engine: Optional[SplitEngine] = None,
        merge_engine: Optional[MergeEngine] = None,
        similarity_evaluator: Optional[SignatureSimilarityEvaluator] = None,
    ):
        self.evaluator = similarity_evaluator or SignatureSimilarityEvaluator()
        self.split_engine = split_engine or SplitEngine()
        self.merge_engine = merge_engine or MergeEngine(
            similarity_evaluator=self.evaluator
        )

    def refine(
        self,
        events: List[EpisodicEvent],
        frames: Optional[List[EpisodeFrame]] = None,
    ) -> List[EpisodicEvent]:
        """
        Executes split and merge post-processing passes on a batch of candidate episodes.

        Args:
            events: Initial EpisodicEvent instances generated by EpisodeBuilder.
            frames: Optional sequence of EpisodeFrames used for frame-level split precision.

        Returns:
            List of finalized, canonical EpisodicEvent objects.
        """
        if not events:
            return []

        # Step 1: Split multi-behavioral episodes
        split_events: List[EpisodicEvent] = []
        for event in events:
            splits = self.split_engine.evaluate_splits(event, frames=frames)
            split_events.extend(splits)

        if not split_events:
            return []

        # Step 2: Merge continuous adjacent episodes
        refined_events = self.merge_engine.evaluate_merges(split_events)

        return refined_events
